package DIU_system3_example;
import java.awt.*;
import simView.*;

/* ========================================================================================================================
 * DATE : 2021/10/05
 * AUTHER : 권보승(bskwon9428@gmail.com)
 * BRIEF : DIU, genr, AMI atomic model로부터 gpt model을 생성한다.
 * 		    [2021/10/20 수정]
 * 			AMI에서 AMI_company를 독립적인 모델로 분리하여 생성한다.
 * ======================================================================================================================== */

public class gpt extends ViewableDigraph
{
	private String[] ami_list = {"out_ami_house", "out_ami_school","out_ami_yh1", "out_ami_yh2", "out_ami_yh3"};

	public gpt()
	{
		super("gpt");
    	
		ViewableAtomic g = new genr("genr", 13);
		ViewableAtomic p = new DIU("DIU", 0);
		ViewableAtomic ac = new AMI_company("ami_c", 0);
		add(p);
		add(ac);
		addCoupling(ac, "out", p, "in");
		addCoupling(p, "out_ami_company", ac, "in");
		for (int i = 1; i<=ami_list.length; i++) {
			ViewableAtomic a = new AMI("ami_"+i, 0); 
			add(a);
			addCoupling(p, ami_list[i-1], a, "in");
			} // 반복문 이용하여 다수의 AMI를 한번에 DIU연결
		add(g); 
		addCoupling(g, "out", p, "in");
		addCoupling(p, "re_request", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("DIU")).setPreferredLocation(new Point(357, 241));
        ((ViewableComponent)withName("ami_2")).setPreferredLocation(new Point(661, 214));
        ((ViewableComponent)withName("ami_c")).setPreferredLocation(new Point(662, 420));
        ((ViewableComponent)withName("ami_3")).setPreferredLocation(new Point(661, 264));
        ((ViewableComponent)withName("ami_5")).setPreferredLocation(new Point(662, 368));
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(137, 110));
        ((ViewableComponent)withName("ami_1")).setPreferredLocation(new Point(660, 162));
        ((ViewableComponent)withName("ami_4")).setPreferredLocation(new Point(661, 316));
    }
}
