package Lab8_HW;
import java.awt.*;

import simView.*;

public class handshake extends ViewableDigraph
{

	public handshake()
	{
		super("handshake");
    	
		ViewableAtomic c = new client("c", 10);
		ViewableAtomic s = new server("s", 10);
    	
		add(c);
		add(s);
  
		addCoupling(c, "out", s, "in");
		addCoupling(s, "out", c, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("s")).setPreferredLocation(new Point(470, 368));
        ((ViewableComponent)withName("c")).setPreferredLocation(new Point(50, 50));
    }
}
