package PMU_system;
import java.awt.*;

import simView.*;

public class gpt extends ViewableDigraph
{

	public gpt()
	{
		super("gpt");
    	
		ViewableAtomic pat = new patient("Patient", 40);
		ViewableAtomic pmu = new PMU("PMU", 20);
		ViewableAtomic om = new OM("OM", 20);
    	
		add(pat);
		add(pmu);
		add(om);
		
		addCoupling(pat, "out", pmu, "in");
		addCoupling(pmu, "pat_out", pat, "in");
		addCoupling(pmu, "om_out", om, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("OM")).setPreferredLocation(new Point(686, 422));
        ((ViewableComponent)withName("PMU")).setPreferredLocation(new Point(415, 169));
        ((ViewableComponent)withName("Patient")).setPreferredLocation(new Point(70, 316));
    }
}
