package Lab9_HW;
import java.awt.*;

import simView.*;

public class gpt extends ViewableDigraph
{

	public gpt()
	{
		super("gpt");
    	
		ViewableAtomic g = new sender("sender", 10);
		ViewableAtomic r = new router("router", 10, 5);
		
    	
		add(g);
		add(r);
  
		addCoupling(g, "out", r, "in");
		addCoupling(r, "out_s", g, "in");

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
		for(int i = 1; i <= 5; i++) {
			ViewableAtomic p = new receiver("receiveer"+i, 10);
			add(p);
			addCoupling(r, "out" + i, p, "in");
		}
	}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(741, 479);
        ((ViewableComponent)withName("receiveer5")).setPreferredLocation(new Point(469, 330));
        ((ViewableComponent)withName("router")).setPreferredLocation(new Point(229, 168));
        ((ViewableComponent)withName("sender")).setPreferredLocation(new Point(35, 190));
        ((ViewableComponent)withName("receiveer3")).setPreferredLocation(new Point(483, 181));
        ((ViewableComponent)withName("receiveer2")).setPreferredLocation(new Point(475, 115));
        ((ViewableComponent)withName("receiveer4")).setPreferredLocation(new Point(467, 252));
        ((ViewableComponent)withName("receiveer1")).setPreferredLocation(new Point(406, 45));
    }
}
