package DIU_system_example;
import java.awt.*;
import simView.*;

/* ========================================================================================================================
 * DATE : 2021/10/05
 * AUTHER : �Ǻ���(bskwon9428@gmail.com)
 * BRIEF : DIU, genr, AMI atomic model�κ��� gpt model�� �����Ѵ�.
 * ======================================================================================================================== */

public class gpt extends ViewableDigraph
{
	private String[] ami_list = {"out_ami_house", "out_ami_school", "out_ami_company", "out_ami_yh1", "out_ami_yh2", "out_ami_yh3"};

	public gpt()
	{
		super("gpt");
    	
		ViewableAtomic g = new genr("genr", 10);
		ViewableAtomic p = new DIU("DIU", 0);
		add(p);
		for (int i = 1; i<=ami_list.length; i++) {
			ViewableAtomic a = new AMI("ami_"+i, 0); 
			add(a);
			addCoupling(p, ami_list[i-1], a, "in");
			} // �ݺ��� �̿��Ͽ� �ټ��� AMI�� �ѹ��� DIU����
		add(g); 
		addCoupling(g, "out", p, "in");
		addCoupling(p, "re_request", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("ami_3")).setPreferredLocation(new Point(661, 264));
        ((ViewableComponent)withName("ami_4")).setPreferredLocation(new Point(661, 316));
        ((ViewableComponent)withName("ami_5")).setPreferredLocation(new Point(662, 368));
        ((ViewableComponent)withName("DIU")).setPreferredLocation(new Point(357, 241));
        ((ViewableComponent)withName("ami_2")).setPreferredLocation(new Point(661, 214));
        ((ViewableComponent)withName("ami_6")).setPreferredLocation(new Point(663, 420));
        ((ViewableComponent)withName("ami_1")).setPreferredLocation(new Point(661, 164));
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(134, 267));
    }
}