package Lab5;
import java.awt.*;


import Lab5.procQ;
import simView.*;

public class efQproc extends ViewableDigraph 
{

	public efQproc()
	{
		super("efp");
		
		ViewableAtomic sp = new procQ("Qproc", 15); //processing time = 15
		ViewableDigraph  expf = new ef("efQproc", 10, 300); //int_arr_time=10, observation time=300

		add(expf);
		add(sp);

		addCoupling(expf, "out", sp, "in");

		addCoupling(sp, "out", expf, "in");
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(980, 644);
        ((ViewableComponent)withName("Qproc")).setPreferredLocation(new Point(561, 257));
        ((ViewableComponent)withName("efQproc")).setPreferredLocation(new Point(50, 50));
    }
 }
