package Lab3;
import java.awt.*;
import simView.*;

public class modified_gpt extends ViewableDigraph
{

	public modified_gpt()
	{
		super("modified_gpt");
    	
		ViewableAtomic g = new genr("g", 30);
		ViewableAtomic p = new proc("p", 55);
		ViewableAtomic t = new transd("t", 1000);
    	
		add(g);
		add(p);
		add(t);
  
		addCoupling(g, "out", p, "in");
		addCoupling(g, "out", t, "ariv");
		
		addCoupling(p, "out", t, "solved");
     
		addCoupling(t, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(825, 589);
        ((ViewableComponent)withName("t")).setPreferredLocation(new Point(394, 379));
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(59, 148));
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(205, 453));
    }
}
