package Lab7;
import java.awt.*;
import simView.*;

public class accumulation_function extends ViewableDigraph
{

	public accumulation_function()
	{
		super("accumulation_function");
    	
		ViewableAtomic g = new user("user", 10);
		ViewableAtomic p = new accumulator("accumulator", 10);
		
		add(g);
		add(p);
		
  
		addCoupling(g, "out", p, "in");
		
     
		addCoupling(p, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("accumulator")).setPreferredLocation(new Point(309, 425));
        ((ViewableComponent)withName("user")).setPreferredLocation(new Point(50, 50));
    }
}
